### ISSUE TITLE
JUCE coomunication geting array params 

### ISSUE THREAD

**Issue by pokjnb** [benediktsailer/BackgroundRenderer#1]
Hi 
I am stuck in the JUCE and unity communication issues and your answer's link is failed which is:
https://gist.github.com/benediktsailer/c30292f7d19bfaef15aba28b04931610  and the original post is : https://forum.juce.com/t/juce-unity-audio-plugin-communication/40784/5

Could you please tell what is the method to solve the problems? really want to know your way...  and sorry to left message here since not sure get reply in JUCE forum..

**Comment by benediktadams** [comment]
Sorry about that, my github handle changed so the link is not valid anymore. Here's a new link:

https://gist.github.com/benediktadams/c30292f7d19bfaef15aba28b04931610

I also updated the topic on the juce forum with it.

**Comment by pokjnb** [comment]
Thanks very much for your efficient reply and your post really gave some clues about the problem!  

I have a simple question that  when calling ur function **std::function<void(int paramIndex, float val)>**, did you only try to get a float parameter from unity? or theoretically can we get any type parameters? like array, list, struct ect.?  

for example, 
**std::function<void(int paramIndex, struct val)>** and **sendMyParameters(int paramIndex, struct val)** in unity, would it work if only change the type?
